# Generated by Django 5.2.7 on 2025-11-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['id'], 'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
    ]
