# Generated by Django 5.2.7 on 2025-11-28 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lessonprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lessonprogress',
            name='unique_user_lesson_progress',
        ),
        migrations.RenameField(
            model_name='lessonprogress',
            old_name='updated_at',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='lessonprogress',
            old_name='user',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='created_at',
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('student', 'lesson'), name='unique_student_lesson_progress'),
        ),
    ]
